[package]
name = "flashlight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.79"
clap = { version = "4.5.4", features = ["derive"] }
dotenv = "0.15.0"
drift = { git = "https://github.com/drift-labs/protocol-v2.git" }
drift-sdk = { git = "https://github.com/drift-labs/drift-rs" }
env_logger = "0.11.3"
log = "0.4.21"
rust = { git = "https://github.com/drift-labs/jit-proxy" }
solana-sdk = "1.14"
thiserror = "1.0.58"
tokio = { version = "1.34.0", features = ["full"] }
