[package]
name = "arb-dex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
drift-sdk = { git = "https://github.com/drift-labs/drift-rs" }
solana-sdk = "1.14"
tokio = { version = "1.34.0", features = ["full"] }
