[package]
name = "exercism-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.20"
rand = "0.8.5"
once_cell = "1.17.1"
num = "0.4.0"
image = "0.24.6"
crossbeam = "0.8.2"

