[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = { workspace = true }
base64 = { workspace = true }
drift = { path = "../drift" }
futures-util = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
solana-client = { workspace = true }
solana-rpc = { workspace = true }
solana-sdk = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
